__mocks__/ably/promises/index.ts
src/Space.mockClient.test.ts
src/Space.ts

Adds a leave method to allow us to leave the Space.
Adds a mock client to allow us to test against the AblyJS SDK.

Add leave method to allow us to leave a public Space and Presence

---

demo/app/components/avatar-stack.ts
demo/app/index.html
demo/app/script.ts
demo/app/style.css
demo/app/tailwind.css
demo/app/utils/dom.ts
demo/app/utils/fake-names.ts
demo/app/utils/gradients.ts
demo/app/utils/url.ts
demo/package-lock.json
demo/package.json
demo/postcss.config.js
demo/tailwind.config.js

- add tailwind
- style the AvatarStack
- add various functionality to the AvatarStack based on our UI spec

Add AvatarStack component demo

---

.npmignore

1. Removes demo folder & related netlify.toml from npm package
2. Removes test.js files and related files from npm package (previously only test.ts files were removed)
**Output before:**
```
npm notice
npm notice 📦  @ably-labs/spaces@0.0.1
npm notice === Tarball Contents ===
npm notice 10.2kB  LICENSE
npm notice 5.0kB   README.md
npm notice 71B     demo/.env
npm notice 79B     demo/.netlify/edge-functions-import-map.json
npm notice 65B     demo/.netlify/functions-serve/ably-token-request/ably-token-request.js
npm notice 793.4kB demo/.netlify/functions-serve/ably-token-request/src/api/ably-token-request/index.js
npm notice 1.3MB   demo/.netlify/functions-serve/ably-token-request/src/api/ably-token-request/index.js.map
npm notice 1.1kB   demo/api/ably-token-request/index.ts
npm notice …
```

[FIX]: Remove unnecessary entries from NPM

---

demo/README.md
demo/app/components/avatar-stack.ts

This fixes the "in a few seconds" bug when overflowed users disconnect in the avatar stack demo

AvatarStack demo shows events from the future

---

src/Locations.ts
src/Space.ts
src/utilities/EventEmitter.test.ts
src/utilities/EventEmitter.ts

Improve typings & add test coverage to our implementation of the EventEmitter.

Event emitter refactor

---

README.md
__mocks__/ably/promises/index.ts
docs/class-definitions.md
package-lock.json
package.json
src/LocationTracker.mockClient.test.ts
src/LocationTracker.ts
src/Locations.ts
src/Space.ts
src/utilities/EventEmitter.ts

Implement LocationTracker in accordance with DR5.
**Requirements**:
A method to observe a given change in locations, removing the boilerplate of doing it in the listener for all locations and making it easy to get all members in a given location
```
const tracker = space.locations.createTracker((change) => 
change.currentLocation?.form == "settings"
);
tracker.on((change) => {});
tracker.members()
```
**Implemented**:
* A LocationTracker class, instantiated by calling `locations.createTracker` with a `LocationTrackerPredicate` that acts as a predicate on the `LocationChange` event data provided by the main `locations` class.
* A dedicated `off` method on the LocationTracker class that identifies the correct function to remove from `locations` using a Map. **Note:** - functions added …

[MMB-77]: Location Tracker

---

demo/app/data/default-slide-data.ts
demo/app/index.html
demo/app/location-tracking/add-location-tracking.ts
demo/app/location-tracking/location-change-handlers.ts
demo/tailwind.config.js

fixup: Remove console logging and add design tweaks for larger screens

---

docs/class-definitions.md
src/Space.mockClient.test.ts
src/Space.ts

Adds `enter` and `leave` events for individual members entering and leaving a Space. 
Jira ticket: https://ably.atlassian.net/browse/MMB-92

Add space enter/leave events

---

src/Cursor.ts
src/CursorBatching.ts
src/CursorDispensing.ts
src/Cursors.mockClient.test.ts
src/Cursors.ts

https://ably.atlassian.net/browse/MMB-114
This allows incoming batches of updates to be emitted as singular updates at intervals of roughly 60 times per second.

[MMB-114] Add CursorDispensing

---

demo/app/components/avatar-stack.ts

Ticket: https://ably.atlassian.net/browse/MMB-100
Note that this PR also updates the date so it recalculates on mouse over, rather than staying static until you get a new event.

[MMB-100] - Update avatar stack label to be prepended with Left

---

demo/app/components/avatar-stack.ts
demo/app/index.html

Show a label with a name for the connected client ("self")

[MMB-98] Show self in avatars

---

docs/class-definitions.md
docs/usage.md

https://ably.atlassian.net/browse/MMB-155
This update brings up to date our usage and class definition docs, along with formatting and structure changes based on feedback.

[MMB-152] Detailed docs updates

---

CHANGELOG.md
CONTRIBUTING.md

Update these files to better reflect the current status quo.

Update CHANGELOG and CONTRIBUTING

---

README.md
docs/usage.md

This PR removes any remaining traces of the locationTracker. Related to #90

chore: Update docs related to tracker

---

README.md

Adds a missing word in the README.

Small fix to README

---

CHANGELOG.md
package-lock.json
package.json
src/Spaces.ts

I added some _very_ basic lines in `CHANGELOG.md`. See the [commits since the last release](https://github.com/ably-labs/spaces/compare/1a0b129322e34dbec5d4f18f8e21d09d2a6fb32e...main), we should try to decide if a) we want to use a change log at this stage and b) if we do, how detailed we expect it to be. The release itself will contain the total number of commits.
Have agreed to cut a new release, and _then_ merge all our docs in. Any other changes we want in for this release, merge them and I can rebase on top.

release: 0.0.13

---

src/Space.test.ts
src/utilities/is.ts

For example:
```javascript
space.subscribe('update', async () => {
const members = await space.members.getAll();
});
```

Support async subscribe callbacks

---

package-lock.json
package.json
rollup.config.mjs

This fixes the IIFE bundle to include nanoid which was previously defined as a global (but it's not trivial to import nanoid via a script tag).
Also add minification to the bundle (part of https://ably.atlassian.net/browse/MMB-154)

CDN bundle updates

---

demo/package-lock.json
demo/package.json

chore: use npm versions in demo

---

package-lock.json
package.json

Remove mock-socket

---

.eslintrc.js
README.md
demo/src/utils/types.d.ts
docs/class-definitions.md
docs/usage.md
examples/avatar-stack.ts
examples/live-cursors.ts
examples/locking.ts
package-lock.json
package.json

Update repo references after the move to the Ably org.

[MMB-127] Update repo references

---

docs/class-definitions.md
src/Cursors.test.ts
src/Space.ts

Update default batch time.
https://ably.atlassian.net/browse/MMB-260

[MMB-260] Update default batch time to 25ms

---

package-lock.json
package.json
src/Errors.ts

Updated `ably-js` to `1.2.45`
Also replace `ErrorInfo` implementation

chore: bump `ably-js` to `1.2.45`

---

package-lock.json
package.json
react/package.json
src/react/contexts/SpacesContext.tsx
src/react/index.ts
src/react/useSpaces.ts
tsconfig.base.json
tsconfig.iife.json

Resolves [SDK-3875](https://ably.atlassian.net/browse/SDK-3875)
[SDK-3875]: https://ably.atlassian.net/browse/SDK-3875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add `SpacesProvider` and `useSpaces`

---

.eslintrc.js
src/Locks.ts
src/react/useLock.ts
src/react/useLocks.ts
src/react/useSpace.ts

Resolves [SDK-3880](https://ably.atlassian.net/browse/SDK-3880)
[SDK-3880]: https://ably.atlassian.net/browse/SDK-3880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add `useLock` and `useLocks` hooks

---

src/react/useCursors.ts

Resolves [SDK-3881](https://ably.atlassian.net/browse/SDK-3881)
[SDK-3881]: https://ably.atlassian.net/browse/SDK-3881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add `useCursors` hook

---

.eslintrc.js
src/react/useLocations.ts

Resolves [SDK-3878](https://ably.atlassian.net/browse/SDK-3878)
[SDK-3878]: https://ably.atlassian.net/browse/SDK-3878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add `useLocations` hook

---

.eslintrc.js
src/Members.ts
src/react/useCursors.ts
src/react/useMembers.ts

Resolves [SDK-3880](https://ably.atlassian.net/browse/SDK-3880)
[SDK-3880]: https://ably.atlassian.net/browse/SDK-3880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: `useMembers` implementation

---

.eslintrc.js
src/Locks.ts
src/Members.ts
src/react/contexts/SpaceContext.tsx
src/react/contexts/SpacesContext.tsx
src/react/types.ts
src/react/useChannelState.ts
src/react/useConnectionState.ts
src/react/useCursors.ts
src/react/useEventListener.ts
src/react/useLocations.ts
src/react/useLock.ts
src/react/useLocks.ts
src/react/useMembers.ts
src/react/useSpace.ts
tsconfig.base.json

Resolves [SDK-3876](https://ably.atlassian.net/browse/SDK-3876)
[SDK-3876]: https://ably.atlassian.net/browse/SDK-3876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: `useSpace` implementation

---

src/Space.test.ts
src/Space.ts
src/Spaces.test.ts
src/Spaces.ts
src/version.test.ts
src/version.ts
tsconfig.base.json

Add agent param

---

README.md
docs/react.md

Resolves [SDK-3899](https://ably.atlassian.net/browse/SDK-3899)
[SDK-3899]: https://ably.atlassian.net/browse/SDK-3899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: react hook for spaces

---

package-lock.json
package.json

Resolves COL-533 (malformed `LEAVE` presence message is sent when `space.leave()` called whilst holding a lock).

[COL-533] Upgrade Ably to 1.2.46

---

.github/workflows/dev-ci.yml

Do not run upload docs actions if env var is not set 

---

README.md

This PR updates the CDN versions listed in the README after the release of version 0.4

[EDU-1637] Update CDN versions to 2+ and 0.4

---

README.md

docs: update CDN link

---

src/Cursors.test.ts
src/Space.ts

See https://ably.atlassian.net/browse/REA-2166
To get full context on this PR read https://ably.atlassian.net/browse/REA-2166?focusedCommentId=63067

Adjust cursors default outboundBatchInterval
