src/Space.mockClient.test.ts, src/Space.test.ts
This test does not require a socket server and can be run only with a mock client.
=> refactor: move .get spec to mockClient suite

src/Space.mockClient.test.ts, src/Space.ts
As we ideated on .enter and subscriptions in space, some code made it in that is not a defined behaviour in the space spec.
This commit aligns it with the spec.
=> Align .enter to current spec

.gitignore, package-lock.json, package.json, vitest.config.ts
Adds a test coverage reporter via vitest.
Run with `npm coverage`
=> feature: add test coverage report

src/Space.ts
As Space now extends EventTarget, there is no need to have an eventTarget field on the instantiated object.
=> FIX: Remove eventTarget: EventTarget as a public member of Space class

.github/workflows/dev-ci.yml
This is so we can see which exact commands have failed on the PR.
=> feature: break up lint github action into separate jobs

__mocks__/ably/promises/index.ts, src/Space.mockClient.test.ts, src/Space.ts, src/Spaces.ts, src/options/SpaceOptions.d.ts, src/utilities/test/fakes.ts
Add a method to watch all changes to `members` in a space.
Note, because of a merge error, this PR also contains the commits from:
- https://github.com/ably-labs/spaces/pull/9
- https://github.com/ably-labs/spaces/pull/10
=> Add .on method

src/Space.mockClient.test.ts, src/Space.ts
This data gives users an opportunity to change the UI based on what specific event was captured, as well as its timestamp.
The main use case here is to get the timestamp for the “leave” event, and show a user as “inactive” before removing them from the members set.
=> [MMB-5 ] add lastEvent to SpaceMember

src/Space.mockClient.test.ts, src/Space.ts, src/utilities/test/fakes.ts
We've removed previously the stringify from the .enter method to keep compatibility with what happens in underlaying APIs.
This .parse was missed from that refactor.
=> bugfix: remove JSON.parse from member transform

src/Space.mockClient.test.ts, src/Space.ts, src/utilities/test/fakes.ts
The previous implementation worked only on mutating the array but never actually dispatched the event.
This was not caught in tests because the matchers in test also kept the reference to the mutated array.
=> Fix members not being removed after timeout

src/Space.mockClient.test.ts, src/Space.ts
[Jira ticket](https://ably.atlassian.net/browse/MMB-52)
[MMB-42 Document](https://docs.google.com/document/d/1nQ-AHLwAvScDiZmpFpf_QMvETAcN1WUFn8NdluJZV8M/edit#)
Motivation: to support multiple connections per client. Adds method to retrieve client by connectionId and basic logic to update the connectionId.
=> [MMB-52] Add support for multiple connections in line with method laid out in MMB-42

.github/workflows/release.yml
It doesn't seem possible to both keep a permanent committed version in package.json and to apply a version to an NPM package from a git tag.
This PR removes the step to apply a version to an NPM package from a git tag.
=> FIX: Remove step to infer release from Git Release

src/Space.mockClient.test.ts, src/Space.ts, src/utilities/EventEmitter.ts, src/utilities/Logger.ts, src/utilities/test/fakes.ts
Adds an EventEmitter based on [ably-js EventEmitter](https://github.com/ably/ably-js/blob/main/src/common/lib/util/eventemitter.ts).  Presence events are now subscribed automatically when creating a space, rather than when creating a listener, fixing MMB-75 and MMB-76 in the process. This means that there is currently no way to create a space without presence events. This is not currently a problem, if it becomes a problem we can add an option to disable it.
=> Use EventEmitter class over EventTarget

demo/app/components/avatar-stack.ts, demo/app/components/feature-display.ts, demo/app/data/default-slide-data.ts, demo/app/index.html, demo/app/location-tracking/add-location-tracking.ts, demo/app/location-tracking/location-change-handlers.ts, demo/app/script.ts, demo/app/shims-svg.d.ts, demo/app/utils/colors.ts, demo/app/utils/gradients.ts, demo/tailwind.config.js, src/Locations.ts, src/Space.ts
This adds location tracking in its most basic/undifferentiated form to the slides demo (no locking, comments, sublocation tracking).
**A suggested starting point to test functionality**:
As usual:
* `npm run start` from the /demo folder as usual
* Visit the page at localhost:8888, copy the full URL as generated
* Paste the URL into an incognito tab
Then:
* In the normal window, click on a text element A in the main slide
* In the incognito window, click on a different text element B in the main slide
* Check that text element B renders with an orange border in the normal window, and that text element A renders with an orange border in the incognito window.
* Click text element A in the incognito window, then click text element A in the incognito window. Check that text element A still …
=> [MMB-61] Add locations to demo

src/Spaces.ts, src/index.ts
`export * from './file.js'` only re-exports named exports.
=> [MMB-88] Fix incorrect default library export

__mocks__/ably/promises/index.ts, docs/class-definitions.md, src/Cursor.ts, src/CursorBatching.ts, src/Cursors.mockClient.test.ts, src/Cursors.ts, src/Space.mockClient.test.ts, src/Space.ts, src/Spaces.test.ts, src/utilities/Constants.ts
Add Live Cursor functionality to Spaces.
A cursor is retrievable by name from the Cursors class, and represents a point on a 2D plane.
The Cursors class emits one kind of event, a `positionsUpdate`, which can be subscribed to via. the cursor `on` method.
A cursor's position can be updated and will be shared with other users.
Sharing a cursor's position with other users is managed by the CursorBatching class, which collects frequent cursor updates to be shared as a batch.
=> Add Live Cursors

src/Cursor.ts, src/CursorBatching.ts, src/Cursors.mockClient.test.ts, src/Cursors.ts, src/utilities/Constants.ts
The ticket is here:
[MMB-64](https://ably.atlassian.net/browse/MMB-64)
**Note:**
This changes the behaviour of the API considerably to work more in line with the [**Alternative Option** on DR7](https://ably.atlassian.net/wiki/spaces/product/pages/2529853584/DR7+Live+Cursor+API#Alternatives-considered.1).
The discussion precipitating this change can be found [here](https://docs.google.com/document/d/1a5VNpyDoHRo4hNvkmDO9Y3xeXMrZ8addBE3ObaCZEIs/edit#).
Most importantly, positionUpdates and dataUpdates are replaced by a single cursorUpdate event, and (differing from the DR) cursor data and position must both be consistently provided to the API.
This is to support:
* `getAll` functionality to retrieve most recent cursors from channel history
* reliable consistency of data, ensuring position …
=> [MMB-64] Set additional data on a cursor

__mocks__/ably/promises/index.ts, src/Cursors.mockClient.test.ts, src/LocationTracker.mockClient.test.ts, src/Locations.mockClient.test.ts, src/Space.mockClient.test.ts, src/Space.ts, src/utilities/test/fakes.ts
Keep Space Members by connection ID, not client ID.
Connection ID does not always exist, however it will always exist as long as Spaces is relevant; therefore, I think this implementation should be feasible.
Check that things still work on this review app:
https://645cb3c6550a247a98488cae--spaces-demo.netlify.app/?space=idea-garden-breathe
=> [MMB-111] Keep Space members by connection ID, not client ID

__mocks__/ably/promises/index.ts, src/CursorHistory.ts, src/Cursors.mockClient.test.ts, src/Cursors.ts
https://ably.atlassian.net/browse/MMB-90
Add method to get the last known position of cursors
This relies on looking through history to find the last cursor position per connection, per named cursor.
The PAGINATION_LIMIT is set here to 5, meaning up to 500 messages will be looked at. This limit might be too small, but I'd rather verge on the more conservative side for now. In the future, we should expose it as an option.
=> [MMB-90] Add method to get the last known position of cursors

docs/class-definitions.md
Small update + formatting fixes
=> Add missing method to class definitions

__mocks__/ably/promises/index.ts, demo/app/components/cursors.ts, demo/app/components/simulate.ts, demo/app/script.ts, src/Cursor.ts, src/CursorBatching.ts, src/CursorDispensing.ts, src/Cursors.mockClient.test.ts, src/Cursors.ts
When a user leaves a tab, all methods that use timers are delayed by the browser, most often to at least a second (or more). Because we dispense cursor positions at 1ms, this has the potential to create a massive backlog of events when a user comes back to that tab. To handle this, we check the `visibilityState` of a tab when processing events. If the tab is hidden, we process them immediately, without the setTimeout (which should be rapid as it would not trigger any repaints).
We also refactor how cursors use channels. Each cursor creates their own subscription, so when we detach we can remove channel subscription together with cursor emitter subscriptions.
=> [MMB-125] All cursor events are repeated fix

docs/class-definitions.md, docs/usage.md, src/CursorDispensing.ts, src/Cursors.mockClient.test.ts, src/Cursors.ts, src/options/CursorsOptions.d.ts, src/utilities/math.ts
This change is meant to help with cursors “stuttering”. On longer intervals, inbound intervals are dispensed a long time before a new batch comes in, creating a gap. Instead, a static option, this attempts to find a good value based on the largest current buffer. This is clamped then between 1ms and 1000/15 (60ms).
This spreads out the values up to batch time (or at least attempts to).
=> Measured position dispensing

package-lock.json, package.json, src/Space.ts, src/Spaces.test.ts, src/Spaces.ts
This PR Updates the type for ClientOptions agent which is an object, not an array.
=> Updates Type for ClientOptions agent

.eslintrc.js, demo/.eslintrc.js, package-lock.json, package.json, src/Cursor.ts, src/CursorBatching.ts, src/CursorDispensing.ts, src/CursorHistory.ts, src/Cursors.mockClient.test.ts, src/Cursors.ts, src/LocationTracker.mockClient.test.ts, src/Locations.mockClient.test.ts, src/Locations.ts, src/Space.mockClient.test.ts, src/Space.ts, src/Spaces.ts, src/options/SpaceOptions.d.ts, src/utilities/EventEmitter.test.ts, src/utilities/test/mock-server.ts
When modules are imported in browsers, they require a file path. Typescript does not amend the imports so we need to do it manually. See https://github.com/microsoft/TypeScript/issues/16577 and in particular https://github.com/microsoft/TypeScript/issues/16577#issuecomment-703190339
Adding also an eslint rule so this is flagged in the future.
=> Add .js extension to imports

package.json, src/LocationTracker.mockClient.test.ts, src/LocationTracker.ts, src/Locations.mockClient.test.ts, src/Locations.ts, src/Space.mockClient.test.ts, src/Space.ts, src/index.ts
Fix initial location being set too eagerly
This fixes a bug where both `previousLocation` and `currentLocation` would be set when .set was called initially.
When setting location, we'd get a handle on the member and update their location. However, because we called .update on the presence, the subscription on the space would trigger as well, get the location and update the member before we emit the location event.
=> [MMB-118] Previous location not set to null for first update

demo/app/components/avatar-stack.ts
This PR changes the hover text for avatars that have left the space from 'Left a few seconds ago' to a more precise 'Last seen _n_ seconds ago'
=> [MMB-103]: Update avatar stack time status

docs/class-definitions.md, docs/usage.md, src/Space.mockClient.test.ts, src/Space.ts, src/utilities/EventEmitter.ts, src/utilities/TypeOf.ts
Add a method to update profile data. https://ably.atlassian.net/jira/software/c/projects/MMB/issues/MMB-171
=> [MMB-171] Update profile data

src/CursorBatching.ts, src/CursorDispensing.ts, src/CursorHistory.ts, src/Cursors.mockClient.test.ts, src/Cursors.ts, src/Space.mockClient.test.ts, src/Spaces.test.ts
This changes the behaviour to only initialise a channel when a developer starts listening to cursor events or sets an update.
=> [MMB-175] Only initialise cursors channel when .on or .set are called

README.md, demo/app/components/cursors.ts, demo/app/script.ts, docs/class-definitions.md, docs/usage.md, src/Cursors.mockClient.test.ts, src/Cursors.ts, src/Locations.mockClient.test.ts, src/Locations.ts, src/Space.mockClient.test.ts, src/Space.ts, src/utilities/EventEmitter.test.ts, src/utilities/EventEmitter.ts
This is done not by updating the names in the EventEmitter, but by proxying the methods in classes. We'd like to keep the API of that class as close as possible to the ably-js one.
Furthermore, we'd like to reserve .on/off for potential, future connection events.
=> [MMB-175] Change on/off to subscribe/unsubscribe

docs/class-definitions.md, src/CursorHistory.ts, src/Cursors.mockClient.test.ts, src/Cursors.ts
This PR adds the following methods to the Cursors:
- `getSelf`
- `getOthers`
Also fixes a typo for `LastPosition`
=> [MMB-180] Add getSelf and getOthers method to cursors

demo/src/App.tsx, demo/src/components/Avatar.tsx, demo/src/components/AvatarStack.tsx, demo/src/components/Header.tsx, demo/src/components/Image.tsx, demo/src/components/Paragraph.tsx, demo/src/components/SlideMenu.tsx, demo/src/components/Title.tsx, demo/src/components/slides.tsx
Fix CSS issues on the demo:
- bump up fonts below the lg breakpoint
- add min-width for the container
- correct sizing for avatars on below lg breakpoint
- display name label on image elements
- position correctly elements on slides below the lg breakpoint
- adjust header spacing
=> CSS demo fixes

README.md
Fixed an issue where in the README [Locations](https://github.com/ably-labs/spaces/blob/main/README.md) section, the code block isn't being closed, which causes the non-code content to be included within a code block.
=> Fixed an issue in README where a code block wasn't being closed

__mocks__/ably/promises/index.ts, examples/locks.ts, package-lock.json, package.json, src/Cursors.test.ts, src/Errors.ts, src/Locks.test.ts, src/Locks.ts, src/Members.ts, src/Space.test.ts, src/Space.ts, src/index.ts, src/types.d.ts, src/utilities/test/fakes.ts, src/utilities/types.d.ts
This is a draft PR to get feedback on an early implementation of Component Locking.
This is not a complete implementation, but opening for early feedback and to align with changes proposed in https://github.com/ably-labs/spaces/pull/101.
**[UPDATE: 2023-08-07]**
I have now implemented all four proposed locking features: Query, Acquire, Release, and Subscribe.
`space.locks.get` is used to query whether a lock identifier is currently locked and by whom. It returns a `Lock` type which has the following fields:
```typescript
type Lock = {
member: SpaceMember;
request: LockRequest;
};
```
For example:
```javascript
// check if the id is locked
const isLocked = space.locks.get(id) !== undefined;
// check which member has the lock
const { member } = space.locks.get(id);
// check the lock …
```
=> Add Component Locking

src/Cursors.test.ts, src/Locks.test.ts, src/Locks.ts, src/Members.ts, src/Space.test.ts, src/types.d.ts, src/utilities/test/fakes.ts
In preparation for `SpaceMember` being retrieved directly from the presenceMap rather than maintained separately (see https://ably.atlassian.net/browse/MMB-182).
[MMB-182]
[MMB-182]: https://ably.atlassian.net/browse/MMB-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> locks: Move lock state out of SpaceMember

src/Leavers.ts, src/Members.ts, src/Space.test.ts
The `Leavers` class is used to track members which have recently gone offline (i.e. they left presence within the last [120s](https://github.com/ably-labs/spaces/blob/main/src/Space.ts#L23)), and they are currently also maintained within the `members` array within the `Members` class until they are finally removed.
We plan to remove the `members` array in favour of loading members directly from the presenceMap (see https://ably.atlassian.net/browse/MMB-182), which means it will no longer contain leavers, and so in preparation for that change, this PR decouples the leavers from the `members` array and instead concats them in `members.getAll()`.
[MMB-182]
[MMB-182]: https://ably.atlassian.net/browse/MMB-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …
=> space: Don't maintain leavers within the members array

src/Locations.test.ts, src/Locks.test.ts, src/Members.ts, src/Space.test.ts, src/Space.ts, src/utilities/test/fakes.ts
Since maintaining a shadow copy of presence state is an anti-pattern, see https://ably.atlassian.net/browse/MMB-182.
This mainly updates the tests so that emitting a presence update message is accompanied by that update being reflected in subsequent calls to `presence.get()`.
[MMB-182]
[MMB-182]: https://ably.atlassian.net/browse/MMB-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> members: Drop the members array in favour of presence.get()

src/Locations.test.ts, src/Locations.ts, src/Locks.ts, src/Space.test.ts, src/Space.ts
Prior to this change, updating profile data or setting location would remove all lock state from presence since `extras` would be set to `null`, which would wrongly release all locks held my the current member.
=> space: Ensure lock state is maintained in presence data

demo/src/components/Cursors.tsx, src/Cursors.test.ts, src/Cursors.ts
The API states that a namespace should use `update` for the event name rather than `cursorUpdate`.
=> Change 'cursorsUpdate' event to 'update'

.github/workflows/cdn.yml
Initially I've added this as a workflow dispatch which requires us to manually do this, but once I've confirmed it works as required we can switch it into `release.yml` to automatically push the new bundle for every new release.
Unfortunately to test actions with a workflow dispatch they must be merged into `main`. 
I suspect I also need to add the secret for the account ID (is it actually secret? who knows!), which I'll need to ask sec team to do.
=> Add GitHub Actions workflow for CDN uploads

.github/dependabot.yml, README.md
A couple of small changes to help prepare for the eventual migration from `ably-labs` organization to `ably`.
1. Add Dependabot configuration, since we should ensure we're keeping dependencies up to date where possible
2. Add the header that is used across all our SDKs
=> [MMB-127] Small changes to prepare for repo migration

.github/workflows/cdn.yml, CONTRIBUTING.md
I tested this on this branch and successfully uploaded the bundle here: https://nonprod-cdn.ably.com/spaces/0.0.12/iife/index.bundle.js
See commits for details.
=> [MMB-154] A few small fixes for CDN publishing

src/Locks.test.ts, src/Locks.ts
To avoid them holding on to their locks indefinitely.
[MMB-234]
[MMB-234]: https://ably.atlassian.net/browse/MMB-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> locks: Release all locks when a member leaves

src/Locks.test.ts, src/Locks.ts
It's in [the original API design](https://ably.atlassian.net/wiki/spaces/product/pages/2668298321/MMDR19+Component+Locking+API#TypeScript-API), but is missing from the implementation, so this adds it.
[MMB-261]
[MMB-261]: https://ably.atlassian.net/browse/MMB-261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> locks: Add space.locks.getAll()

README.md, docs/class-definitions.md, docs/usage.md
=> Further docs updates based on Laura's base work on new API updates

.github/workflows/cdn.yml
I mistakenly thought cdn.ably.com was using the new bucket, but it's actually using the old bucket. Until we are migrated we will need to also upload files to the old bucket.
Required PR: https://github.com/ably/infrastructure/pull/6292
=> Add legacy CDN upload

CONTRIBUTING.md, README.md, docs/class-definitions.md, docs/usage.md
Update docs to use the latest API.
=> [MMB-219] Update docs

src/Cursors.ts, src/Errors.ts, src/Locations.ts, src/Locks.ts, src/Space.ts, src/Spaces.ts, src/utilities/EventEmitter.ts
The majority of errors we are throwing are default InvalidArgumentError type errors.
Otherwise, we only really have two other errors:
1. Attempting to connect to a space where the name is missing
2. Trying to do something when they have entered a space
I've copied the way that locks used errors.
=> [MMB-44] Ensure we're setting proper error codes

package-lock.json, package.json
Right now we need to rely on bundler deduplication algorithm to have single instance of `ably`, and we don’t have any guarantees, especially if there is lazy-loading. But current locking implementation heavily depends on single `ably` and breaks everything if space's `ably` is not equal to client's `ably`
=> chore!: make `ably` peer dependency

src/types.ts, src/utilities/test/fakes.ts, src/utilities/types.ts
`.d.ts` files designed to be backed by `.js` files, using them just for type declaration can lead to type errors after the compilation
=> fix: rename `types.d.ts` to `types.ts`

src/Cursors.test.ts, src/Cursors.ts, src/Members.ts, src/Space.test.ts
This makes `get*` methods consistent, always returning `null` instead `undefined` when no values are found.
=> Prefer null over undefined consistently

src/CursorBatching.ts, src/CursorHistory.ts, src/Cursors.test.ts
This broke when we added offsets to the OutgoingBuffer in cursors. Unfortuntely, the relevant tests need to mock the whole presence message and did not catch this change.
When we implement integration tests, this should be a prime candidate for a golden path test as it needs to go via multiple separate modules as well as Ably.
=> Fix getAll no returing position or data values

src/Locks.test.ts, src/Locks.ts, src/index.ts, src/types.ts, src/utilities/types.ts
Move properties from the request key to the lock.
Having the request property proved to be not-intuitive and wordy.
=> [MMB-264] Flatten the lock type

README.md, docs/class-definitions.md, package.json
This adds a Component Locking section to the README inline with the description from the PR which introduced the feature (https://github.com/ably-labs/spaces/pull/102).
The documentation is intentionally light on context and is subject to change over the coming weeks as we iterate on the feature.
=> docs: Add Component Locking section to README

README.md, docs/class-definitions.md, docs/usage.md, src/Members.test.ts, src/Members.ts, src/Space.test.ts
This change bring "update" inline with how we describe "update" in the docs - as an events that catches all events, instead of just profile updates.
To accomodate only profile update changes, an updateProfile event was added.
This is based on feedback, where users found that "update" did was inconsistent with other APIs.
=> [MMB-275] Update members update event

src/Cursors.ts, src/Errors.ts, src/Locations.ts, src/Locks.ts, src/Space.ts, src/Spaces.ts
JavaScript stack straces are created upon initialisation of the `Error` object, so when errors are initialised ahead of the time they are thrown, the stack trace will not show the context of where/why the error was thrown, only the context of how the `Errors.ts` module was first loaded.
We used to do the same thing in ably-js until someone pointed out that they were getting misleading stack traces, see: 
- [Issue raised by third party](https://github.com/ably/ably-js/issues/1202)
- and [PR to fix it](https://github.com/ably/ably-js/pull/1206)
=> refactor: avoid early initialisation of common errors

demo/src/components/SpacesContext.tsx, demo/src/main.tsx, src/Errors.ts, src/Locks.test.ts, src/Locks.ts, src/Spaces.ts
Unlock update hasn't triggered after lock release
Added emitting `'update'` event after lock released 
---
**Update:** I've updated this to a different fix. When you `get` a lock, it's not valuable to get `unlocked` locks - these are only useful in listeners. So the change here, which fixes the above bug, is to make sure we clear any unlocked locks, but send them in presence to process. After processing, the lock is clear. This makes the logic to compare if an event should be fired work (otherwise the mutated state is equal to the processed state and nothing happens locally).
=> fix: unlock update hasn't triggered after lock release

docs/channel-usage.md, src/Cursors.ts, src/Space.test.ts, src/Space.ts, src/Spaces.test.ts
- update cursors channels to a tagged channel
- update space channel to a suffix, so later can be easily chaged to a tagged channel
https://ably.atlassian.net/browse/MMB-247
=> [MMB-247] Channel tagging

src/Cursors.test.ts, src/Cursors.ts
The cursor batching algorithm was designed so that the overall channel message rate remains lower than an upper bound limit, and the algorithm expects the batching to multiply the batch interval by the number of members, not the number of members minus one as we're currently doing.
=> cursors: Fix cursor batching calculation

src/Locations.ts, src/Locks.ts, src/Space.test.ts, src/Space.ts, src/SpaceUpdate.test.ts, src/SpaceUpdate.ts
This refactors space updates so we have a single class responsible for managing the shape of the updates.
This also fixes:
- `updateProfileData` not passing an argument to the update function (see @snikidev 's report)
- `.leave` resetting profileData for users when no arguments are passed in https://ably.atlassian.net/browse/MMB-303
=> Refactor space updates

src/index.ts
This unused export would make rollup create an object instead of a constructor for the IIFE bundle.
=> Remove unused export

demo/noop.js, demo/vite.config.ts
See https://github.com/vitejs/vite/issues/9200 (this is only happening in dev mode)
=> Silence Vite warnings about node packages loaded by postcss

demo/src/hooks/useElementSelect.ts, demo/src/utils/locking.ts, src/Locks.ts
Whilst working on MMB-156 I asked whether this was meant to be part of the public API and was told no, and that its usage should be replaced by `Locks.prototype.getSelf`.
I have no idea whether the `delay(60)` preceding the call to `releaseMyLocks` in the `useElementSelect` hook is still necessary, since I don’t know what the "spaces API" that it refers to is.
=> Make `Locks.prototype.getLocksForConnectionId` private

src/index.ts
This reverts commit b882b4a44191de91d5e424ede7ccd9d7f3a3af63.
Although this fixes our CDN build, `LockAttributes` can't be removed as that would make them unavailable in the public API.
Reverting so we can release and work on a proper fix for both issues.
=> Revert "Remove unused export"

demo/package-lock.json, demo/package.json, demo/src/components/CurrentSlide.tsx, demo/src/components/Cursors.tsx, demo/src/hooks/useMembers.ts, demo/src/hooks/useTrackCursor.ts
- fixes `cursors.set` throwing an error because we call it before a space was entered
- fixes cursors not being removed after a user has left
=> Fix cursors demo issues

demo/package-lock.json, demo/package.json, demo/src/utils/locking.ts
- updates the ably/spaces version used to 0.1.3
- fixes the "release all locks" method in demo (it would't work because `getSelf` is async)
=> Demo updates

.husky/pre-commit, package-lock.json, package.json
Whilst I am a strong believer in making sure that each commit conforms to formatting rules and that its tests pass, I have found that the downsides of using Husky to enforce this outweigh the benefits.
In particular, I have my own set of personal Git hooks that I use as part of my development workflow, and have configured my global `core.hooksPath` so that they are applied across all repositories that I work with. However, when I run `npm install` inside this repo, Husky then comes along and — without even giving me a warning that it’s going to do so — sets the repo’s local `core.hooksPath` to its own value, silently disabling my personal hooks.
As far as I can tell, there is no way for Husky to nicely co-exist with personal Git hooks. With this in mind, I would prefer we remove Husky and …
=> Remove Husky

src/utilities/EventEmitter.test.ts, src/utilities/EventEmitter.ts
This copies across the change from https://github.com/ably/ably-js/pull/1453 — see explanation there.
The removed code in the current PR also had a bug — the second argument in the removed code `self.off(eventName, this)` was incorrectly populated and this made the removed code equivalent to `self.off(eventName)`; that is, it removed _all_ listeners for the given event name. I believe that the removal of this code accounts for the increased expected number of calls to `context.spy` in one of the tests here. I’m not sure what reasoning led to the previous expected count of 3 (perhaps the expectation was written just based on the number of calls observed when running the code), but here’s my reasoning for the expectation of 4 calls:
Before `context.eventEmitter['off']('myEvent', …
=> Remove ability to pass array of event names to `EventEmitter.prototype.once`

package-lock.json, package.json
We have a `coverage` command in `package.json` but somehow the actual coverage package never made it into dependencies.
=> Add missing package for code coverage

docs/class-definitions.md, src/Locks.test.ts, src/Locks.ts, src/index.ts
Resolves [MMB-317](https://ably.atlassian.net/browse/MMB-317) and [MMB-318](https://ably.atlassian.net/browse/MMB-318).
I have chosen to simply remove the `LockAttributes` class and replace it with `Record<string, unknown>`, which is what we use elsewhere for representing arbitrary key-value pairs in the public API of the SDK.
See https://github.com/ably/docs/pull/2023 for corresponding documentation update.
[MMB-317]: https://ably.atlassian.net/browse/MMB-317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MMB-318]: https://ably.atlassian.net/browse/MMB-318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MMB-317], [MMB-318] — Remove the `LockAttributes` type

docs/class-definitions.md, src/Cursors.ts, src/Locations.ts, src/Locks.ts, src/Members.ts, src/Space.ts, src/index.ts, src/types.ts, src/utilities/EventEmitter.test.ts, src/utilities/EventEmitter.ts, src/utilities/is.ts, src/utilities/types.ts
This introduces an assortment of refactorings intended to make it easier to perform MMB-156 (adding documentation comments). See commit messages for more details.
=> [MMB-156] Prepare for adding documentation comments

__mocks__/ably/promises/index.ts, package.json, src/Locations.test.ts, src/Locks.test.ts, src/Space.test.ts, src/Space.ts
This fixes a bug where `space.enter()` would sometimes hang. See commit messages for more details.
=> [COL-335] Fix bug where `space.enter()` sometimes hangs.

demo/src/components/Cursors.tsx, src/react/useCursors.test.tsx, src/react/useCursors.ts, src/react/useLocations.ts, src/react/useLocks.ts, src/react/useMembers.test.tsx, src/react/useMembers.ts
add `useCursors` variant without callback
=> fix: `useLocations`,`useMembers` hook overload

src/Locks.test.ts, src/Locks.ts
https://ably.atlassian.net/browse/COL-333
When a lock is retrieved by using locks.get, a reference to an object is returned. By mutating this reference, a developer, could in theory, mutate the lock held by Spaces. This could lead to subtle and hard to debug issues.
This commit changes the .get and .getAll methods to return copies of objects instead. This breaks some of the internal mutations, so they are replaced by the already present .setLock method which will override the lock with a new object, severing any dependecies on references.
=> [COL-333] Return value of a lock not it's reference

.github/workflows/dev-ci.yml, CONTRIBUTING.md, test/cdn-bundle/test/cdnBundle.test.ts, test/integration/integration.test.ts, test/integration/utilities/setup.ts, test/lib/ablySandbox.ts, test/lib/tsconfig.json
This adds integration tests that test the core functionality of the SDK. It's currently a draft so I can get feedback on the approach and some of the questions that came up whilst I was working in this (see `TODO` comments in code).
<del>On top of what's currently here, I intend to also add a test for component locking.</del> (I've added a component locking test, too.)
=> [COL-56] Add integration tests (WIP)

docs/channel-usage.md, src/Space.test.ts, src/Space.ts, src/Spaces.test.ts
::$space is a channel tag and has special meaning within Ably, unlike the suffix `-space`.
=> [COL-577] Use ::$space as space channel suffix

src/react/useCursors.test.tsx
Fixed test. That's odd, for some reason updates on members started coming a bit later, don't know why, but it should be a problem for hooks.
=> fix: useCursors test with newest ably-js

src/Cursors.ts, src/Locations.ts, src/Locks.ts, src/Members.ts, src/Space.ts, src/Spaces.ts, src/types.ts, src/utilities/EventEmitter.ts
This PR updates all docstring comments. Broadly speaking, it:
* Consolidates the content taken from the docs site and class definitions.
* Removes labels of where content was sourced from. 
* Makes comments consistent where appropriate.
=> [COL-526] Update and consolidate docstring comments

src/Spaces.test.ts, src/Spaces.ts
The spaces SDK needs only one Ably-Agent entry, `spaces`, so this replaces the current `ably-spaces` with `spaces` in the `agents` client options, and removes the unnecessary `space-custom-client` entry.
=> Fix Ably-Agent usage

.github/dependabot.yml, demo/package-lock.json, demo/package.json, package-lock.json, package.json
Resolves #306
Starting from nanoid v4, it only works with ESM projects. We need to support both CJS and ESM bundles for the `spaces` SDK, so we have the following options to use the nanoid package:
1. Replace `require('nanoid')` imports with async `await import('nanoid')`. This solution is not suitable as the methods we currently use nanoid in are not async, and changing them to async will create cascading effects for a bunch of other methods and change the public API for users.
2. Replace the nanoid package with an in-project utility function to generate ids. This may be undesired since nanoid uses different `crypto` packages for its browser and Node.js bundles with some other platform-specific optimizations. Including them locally would not be a trivial change.
3. Downgrade to using …
=> Downgrade to using nanoid@3 to support its use in CJS module bundle

src/Cursors.test.ts, src/Cursors.ts
https://ably.atlassian.net/browse/REA-1868
This PR changes the rate at which we adapt the (client-side) batch time, multiplying the `outboundBatchInterval` by slots of 100s instead of multiplying this value with the number of presence members.
This change and smoothing of client-side batching interval is incentivised by the addition of server-side batching, which is now enabled by default for cursors channels.
=> Change cursors batch time formula on presence update

src/Space.ts
Instead of assigning the connectionId once in the space's constructor, it should be taken directly from the ably client. This ensures that the connectionId stays in sync even after a disconnect e.g. when the machine hibernates.
=> fix: stale connectionId
